"""
Master Planner for Mourne.
Decomposes a creative script into granular visual steps for media generation.
"""
import json
from typing import Optional
from .llm_backend import get_planner_llm, OpenRouterLLM
from .models import MasterPlan, SceneStep, MediaType


PLANNER_SYSTEM_PROMPT = """You are a Master Video Planner for cinematic AI-generated music videos.
You break down creative scripts into granular visual scenes that can be generated by AI.

Your output must be valid JSON that follows the exact schema provided.
Be creative, cinematic, and precise with timing."""


PLANNER_PROMPT_TEMPLATE = """
Given a creative script and audio analysis, break it down into GRANULAR visual scenes.
Each scene should be 2-8 seconds and represent a single visual moment.

**Input:**
- Script/Concept: {script}
- Audio/Lyrics Analysis: {audio_analysis}
- Total Duration: {duration} seconds

**Output Format (JSON):**
{{
    "project_name": "A creative name for this video project",
    "total_duration": {duration},
    "scenes": [
        {{
            "scene_number": 1,
            "description": "Brief narrative description of what happens",
            "time_start": 0.0,
            "time_end": 4.0,
            "suggested_media_type": "image",
            "visual_prompt_draft": "Detailed visual prompt for AI generation - be VERY specific about composition, lighting, style",
            "audio_context": "What's happening in the audio at this moment",
            "mood": "emotional tone (e.g., melancholic, energetic, ethereal)",
            "suggested_transition": "crossfade"
        }},
        ...more scenes to cover the ENTIRE duration...
    ]
}}

**Rules:**
1. Use "video" for dynamic moments (movement, action, camera motion, transitions between states)
2. Use "image" for static/contemplative moments (can apply Ken Burns effect later)
3. Visual prompts should be HIGHLY detailed and cinematic:
   - Describe camera angle (close-up, wide shot, aerial, dutch angle)
   - Describe lighting (golden hour, neon glow, chiaroscuro, soft diffused)
   - Describe style (photorealistic, anime, oil painting, film noir)
   - Describe specific details (textures, colors, atmosphere)
4. Ensure scenes cover the ENTIRE duration with no gaps
5. Match visual mood to audio mood precisely
6. Each scene's time_end should equal the next scene's time_start
7. Transitions: "fade", "crossfade", "cut", "zoom", or "slide"

Return ONLY valid JSON. No explanation, no markdown code blocks.
"""


class MasterPlanner:
    """
    Decomposes a creative script into granular visual steps.
    Each step becomes a sub-agent task for media generation.
    """
    
    def __init__(self, llm: Optional[OpenRouterLLM] = None):
        self.llm = llm or get_planner_llm()
    
    async def create_plan(
        self, 
        script: str, 
        audio_analysis: str, 
        duration: float
    ) -> MasterPlan:
        """
        Generate a complete scene-by-scene plan.
        
        Args:
            script: The creative concept or script for the video
            audio_analysis: Transcription or description of the audio track
            duration: Total video duration in seconds
        
        Returns:
            MasterPlan with ordered list of SceneSteps
        """
        
        prompt = PLANNER_PROMPT_TEMPLATE.format(
            script=script,
            audio_analysis=audio_analysis,
            duration=duration
        )
        
        result = await self.llm.generate_json(
            prompt=prompt,
            system=PLANNER_SYSTEM_PROMPT,
            temperature=0.6
        )
        
        # Parse scenes into structured models
        scenes = []
        for scene_data in result.get("scenes", []):
            # Handle media type parsing
            media_type_str = scene_data.get("suggested_media_type", "image").lower()
            media_type = MediaType.IMAGE if media_type_str == "image" else MediaType.VIDEO
            
            scene = SceneStep(
                scene_number=scene_data["scene_number"],
                description=scene_data["description"],
                time_start=float(scene_data["time_start"]),
                time_end=float(scene_data["time_end"]),
                suggested_media_type=media_type,
                visual_prompt_draft=scene_data["visual_prompt_draft"],
                audio_context=scene_data.get("audio_context", ""),
                mood=scene_data.get("mood", "neutral"),
                suggested_transition=scene_data.get("suggested_transition")
            )
            scenes.append(scene)
        
        # Sort by time_start to ensure correct order
        scenes.sort(key=lambda s: s.time_start)
        
        plan = MasterPlan(
            project_name=result.get("project_name", "Untitled Project"),
            total_duration=float(result.get("total_duration", duration)),
            scenes=scenes
        )
        
        # Validate coverage
        if not plan.validate_coverage():
            print("Warning: Scene plan has gaps or doesn't cover full duration")
        
        return plan
    
    async def refine_plan(
        self, 
        plan: MasterPlan, 
        feedback: str
    ) -> MasterPlan:
        """
        Refine an existing plan based on user feedback.
        
        Args:
            plan: The current plan to refine
            feedback: User feedback on what to change
        
        Returns:
            Refined MasterPlan
        """
        
        current_plan_json = plan.model_dump_json(indent=2)
        
        prompt = f"""
Here is the current video plan:
{current_plan_json}

User feedback to incorporate:
{feedback}

Please refine the plan based on this feedback. Maintain the same JSON structure.
Return the complete refined plan as JSON.
"""
        
        result = await self.llm.generate_json(
            prompt=prompt,
            system=PLANNER_SYSTEM_PROMPT,
            temperature=0.5
        )
        
        # Parse into MasterPlan (same logic as create_plan)
        scenes = []
        for scene_data in result.get("scenes", []):
            media_type_str = scene_data.get("suggested_media_type", "image").lower()
            media_type = MediaType.IMAGE if media_type_str == "image" else MediaType.VIDEO
            
            scene = SceneStep(
                scene_number=scene_data["scene_number"],
                description=scene_data["description"],
                time_start=float(scene_data["time_start"]),
                time_end=float(scene_data["time_end"]),
                suggested_media_type=media_type,
                visual_prompt_draft=scene_data["visual_prompt_draft"],
                audio_context=scene_data.get("audio_context", ""),
                mood=scene_data.get("mood", "neutral"),
                suggested_transition=scene_data.get("suggested_transition")
            )
            scenes.append(scene)
        
        scenes.sort(key=lambda s: s.time_start)
        
        return MasterPlan(
            project_name=result.get("project_name", plan.project_name),
            total_duration=float(result.get("total_duration", plan.total_duration)),
            scenes=scenes
        )
